NUM_VALID_OBSTACLES: 20
OFFSET: 1.0
RADIUS: 0.4
CSV_FILES:
# - readme_example/baseline.csv
# - poc_readme/baseline.csv
- jan_14/baseline.csv
MODEL_PATHS: 

# - created_models/gauss_2_200_sym     # or an absolute dir path
# - created_models/readme_example_large # can be a directory name under ~/ros_ws/created_models/
# - created_models/cnn_sym
# - created_models/cnn
- "created_models/gauss_2_asym_combo"     # or an absolute dir path
WORLD_NUMS: [12, 36, 75, 125, 203, 210, 69, 187, 266]
# WORLD_NUMS: [12, 36, 75]
NUM_TRIALS: 5
RESET_DELAY: 3
RANDOM_WALK_BAG_DKR: readme_example 
TRAINING_DKR: ros_bag/readme_example
ASYM_FLAG: 1
