
# Robot/config bits (unchanged)
NUM_VALID_OBSTACLES: 20
OFFSET: 1.0
RADIUS: 0.4

# NEW: per-model lists
CSV_FILES:

  - "gauss_2_mlp_adaptive_11_03/baseline.csv"
  # - "results_oct10_different_sliding_window/baseline.csv"
  # - "results_oct8/baseline.csv"
  # - "results_oct15_mlp_asym_sym_runtime/baseline.csv"
  # - "results_oct15_mlp_sym_sym_runtime/baseline.csv"
  # - "results_oct15_cnn_sym_sym_runtime/baseline.csv"
  # - "results_oct15_cnn_asym_sym_runtime/baseline.csv"
  

MODEL_PATHS:
  - "created_models/gauss_2_asym_combo"         # can be a directory name under ~/ros_ws/created_models/
  # - "created_models/gauss_2_200_sym"     # or an absolute dir path
  # - "created_models/cnn_sym"
  # - "created_models/cnn"

# Worlds & trials
WORLD_NUMS: [12, 36, 75, 125, 203, 210, 69, 187, 266]
# WORLD_NUMS: [125, 203, 210, 69, 187, 266]
# WORLD_NUMS: [266]
NUM_TRIALS: 10
RESET_DELAY: 5
# Optional names if you use bags per model (unchanged if you donâ€™t)
BAG_DKR: "gauss_2_noisy"
TRAINING_DKR: "ros_bag/gauss_2_sym_noise"
